### ISSUE TITLE
Unable to upgrade orderNotesForm.html to SDK v2

### ISSUE THREAD

**Issue by BobGerman** [microsoft/app-camp#1]
When upgrading to the Teams JavaScript SDK v2 I was unable to get the microsoftTeams.tasks.submitTask(orderFormInfo) function working with the v2 SDK. Page works as-is with the old SDK.

https://github.com/microsoft/app-camp/blob/main/src/extend-with-capabilities/TaskModule/client/pages/orderNotesForm.html

**Comment by rabwill** [comment]
I can have a look @BobGerman

**Comment by rabwill** [comment]
Looks like this one is not back compatible and we may have to change to dialog. I can confirm with Engg team.

**Comment by rabwill** [comment]
https://github.com/microsoft/app-camp/pull/39 @BobGerman  a workaround has been added which is to pass the appId which is an option parameter in the new dialog.submit. I think we can make this work for the lab.

https://github.com/OfficeDev/microsoft-teams-library-js/issues/1211
