### ISSUE TITLE
`HOSTNAME` key value mentioned wrong in the docs

### ISSUE THREAD

**Issue by arjunumenon** [microsoft/app-camp#117]
The key value mentioned in the **Configure App Settings** section of the A Path lab is wrong.

Hostname in the .env variable is [supposed to be](https://github.com/microsoft/app-camp/blob/708e753cdee20357c926b71337b7d524d4217ab4/src/create-core-app/aad/A01-begin-app/server/server.js#L104) `HOST_NAME` rather than HOSTNAME which is mentioned in the [docs page ](https://microsoft.github.io/app-camp/aad/A01-begin-app/#step-4-configure-the-app-settings).

Though the [sample env file](https://github.com/microsoft/app-camp/blob/main/src/create-core-app/aad/A01-begin-app/.env_Sample) has the right key values, in the [docs](https://microsoft.github.io/app-camp/aad/A01-begin-app/#step-4-configure-the-app-settings) it is mentioned wrong which needs to be corrected.

I can initiate a PR which fixes that issue. Let me know if that works for you

**Comment by rabwill** [comment]
Good catch @arjunumenon that would be great if you can initiate a PR , thank you!

**Comment by arjunumenon** [comment]
Thanks @rabwill . Already initiated the PR.
